# Generated by Django 4.2.6 on 2023-12-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profiles/default/avatar.png', upload_to='profiles/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(default='profiles/default/cover.png', upload_to='profiles/covers'),
        ),
    ]
